global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'api-gateway'

  - job_name: 'services'
    static_configs:
      - targets:
          - 'produtos-service:8080'
          - 'carrinho-service:3000'
          - 'pedidos-service:3000'
          - 'auth-service:3000'
          - 'pagamento-service:3001'  # Nova entrada

rule_files:
  - alerts.yml