global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx-exporter:9113']
        labels:
          service: 'api-gateway'

  - job_name: 'services'
    static_configs:
      - targets: ['produtos-service:3001', 'carrinho-service:3002', 'pedidos-service:3003']

rule_files:
  - alerts.yml